# Pleas verify that this settings are okay!
# If they are okay, replace 'false' with 'true'
enable: false

local: german
database:
  driver:
    id: UPRO-SQLITE-DRIVER
    
world:
  chunk:
    restore:
      use: true
      dont-record:
        - NONE
version: 5