CREATE TABLE IF NOT EXISTS CP (X INTEGER UNIQUE NOT NULL, Y INTEGER UNIQUE NOT NULL, VARCHAR WORLD VARCHAR UNIQUE NOT NULL, REGION VARCHAR UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS PR (REGION VARCHAR UNIQUE NOT NULL, WORLD VARCHAR UNIQUE NOT NULL, PCR BLOB NOT NULL);